name: Flutter Desktop Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: 'stable'
          cache: true

      - name: Install project dependencies
        run: flutter pub get
      - name: Generate intermediates
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Enable windows build
        run: flutter config --enable-windows-desktop
      - name: Build artifacts
        run: flutter build windows --release
      - name: Package Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: Negate-${{github.ref_name}}-windows.zip
          directory: build/windows/runner/Release

      - name: Upload Windows Release
        uses: actions/upload-artifact@v2
        with:
          name: 'Negate Windows'
          path: "build/windows/runner/Release/Negate-${{github.ref_name}}-windows.zip"
